<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>1.0.1-alpha</Version>
        <Title>BoTech.ApiClient.Base</Title>
        <Authors>www.botech.dev</Authors>
        <Description>Some base classes to help developers build api clients.</Description>
        <Copyright>© 2026 www.botech.dev All Rights Reserved!</Copyright>
        <PackageProjectUrl>www.botech.dev</PackageProjectUrl>
        <PackageIcon>BoTechLogoSmall.png</PackageIcon>
        <RepositoryUrl>https://github.com/BoTech-Development/BoTech.ApiClient.Base</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\BoTechLogoSmall.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BoTech.HttpClientHelper" Version="1.0.2-Alpha" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <None Update="BoTechLogoSmall.drawio.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
